version: "3.7"

services:
  postgres_13:
      container_name: postgres_13
      image: postgres:13
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_HOST=postgres
        - POSTGRES_DB=postgres
      ports:
        - '5430:5432' 
          
  streamlit:
    container_name: streamlit
    build: .
    ports:
      - 8501:8501
    volumes: 
      - ./src:/app/src
      - ./app/streamlit_app.py:/app/streamlit_app.py
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres_13
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - postgres_13
  
